# Generated by Django 4.0.1 on 2022-01-10 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('pseudonym', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('second_name', models.CharField(blank=True, max_length=200)),
                ('third_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=5000)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ManyToManyField(blank=True, to='tracks.Artist')),
                ('genres', models.ManyToManyField(blank=True, to='tracks.Genre')),
            ],
        ),
    ]
