# Generated by Django 4.0.1 on 2022-01-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='genres',
            new_name='genre',
        ),
    ]
