# Generated by Django 4.0.1 on 2022-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_rename_genre_track_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='tracks.Track'),
        ),
    ]
