# Generated by Django 4.0.1 on 2022-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='d efault.jpg', null=True, upload_to=''),
        ),
    ]
